# Generated by Django 4.2.11 on 2024-05-03 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_il_ilce'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='il',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.il', verbose_name='İl'),
        ),
        migrations.AddField(
            model_name='customer',
            name='ilce',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.ilce', verbose_name='İlçe'),
        ),
    ]
