# Generated by Django 4.2.11 on 2024-05-06 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_customer_il_customer_ilce'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Tarih')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.customer', verbose_name='Müşteri')),
                ('sales_representative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.salesrepresentative', verbose_name='Satış Temsilcisi')),
            ],
        ),
    ]
